const genres = {
  ACTION_ADVENTURE: 'action-adventure',
  ANIMATION: 'animation',
  AVANT_GARDE: 'avant-garde',
  COMEDY: 'comedy',
  CRIME: 'crime',
  DOCUMENTARY: 'documentary',
  DRAMA: 'drama',
  FANTASY: 'fantasy',
  FILM_NOIR: 'film-noir',
  HORROR: 'horror',
  MUSICAL: 'musical',
  ROMANCE: 'romance',
  SAMURAI: 'samurai',
  SCIENCE_FICTION: 'science-fiction',
  SHORTS: 'shorts',
  SILENT: 'silent',
  THRILLER: 'thriller',
  WAR: 'war',
  WESTERN: 'western',
};
